/* CloudLens AutoPilot for AWS — landing site behaviors */
(function () {
  'use strict';

  // ----- THEME -----
  // Default to light mode on first visit. If the user explicitly toggles to
  // dark, that preference is saved to localStorage and respected on return.
  var root = document.documentElement;
  var stored = localStorage.getItem('cl-theme');
  var theme = stored || 'light';
  root.setAttribute('data-theme', theme);

  var toggle = document.getElementById('theme-toggle');
  if (toggle) {
    toggle.addEventListener('click', function () {
      var next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', next);
      localStorage.setItem('cl-theme', next);
    });
  }

  // ----- WIZARD: live terraform.tfvars preview -----
  // The form fields are re-used from the original ansible-azure template but
  // semantically remapped for AutoPilot AWS Terraform variables:
  //   clms-ip       -> CLMS public IP (for Phase 2 manual configuration ref)
  //   project-key   -> CLMS project key (Phase 2 ref)
  //   tags          -> resource tags
  //   rgs           -> allowed CIDR list (comma-separated)
  //   mode          -> deployment mode: "greenfield" or "existing-vpc"
  var clmsIp = document.getElementById('clms-ip');
  var projKey = document.getElementById('project-key');
  var tags = document.getElementById('tags');
  var rgs = document.getElementById('rgs');
  var mode = document.getElementById('mode');
  var tfvarsOut = document.getElementById('yaml-preview'); // kept ID for CSS continuity

  function quote(s) { return '"' + String(s).replace(/"/g, '\\"') + '"'; }

  function buildTfvars() {
    var clmsIpVal = (clmsIp && clmsIp.value ? clmsIp.value.trim() : '') || '10.0.0.10';
    var projKeyVal = (projKey && projKey.value ? projKey.value.trim() : '') || 'paste-from-clms-projects-api-keys';
    var tagsValue = (tags && tags.value ? tags.value.trim() : '') || 'Env=AWS,Owner=cloudlens';
    var cidrList = (rgs && rgs.value ? rgs.value.split(',').map(function (s) { return s.trim(); }).filter(Boolean) : []);
    if (!cidrList.length) cidrList = ['0.0.0.0/0'];
    var modeVal = (mode && mode.value) || 'greenfield';

    // Build a tags map literal
    var tagPairs = [];
    tagsValue.split(',').forEach(function (pair) {
      var p = pair.trim();
      if (!p) return;
      var eq = p.indexOf('=');
      if (eq > 0) tagPairs.push([p.slice(0, eq).trim(), p.slice(eq + 1).trim()]);
    });
    if (!tagPairs.length) tagPairs = [['Env', 'AWS'], ['Owner', 'cloudlens']];

    var lines = [];
    lines.push('# terraform.tfvars');
    lines.push('# Generated by keysight-tech.github.io/cloudlens-autopilot-docs');
    lines.push('# Place this file at: cloudlens-autopilot/terraform/environments/demo/demo.tfvars');
    lines.push('');
    lines.push('# ----- AWS Region & Profile -----');
    lines.push('aws_region   = ' + quote('us-east-1'));
    lines.push('aws_profile  = ' + quote('default'));
    lines.push('');
    lines.push('# ----- Deployment Identity -----');
    lines.push('prefix       = ' + quote('demo'));
    lines.push('owner        = ' + quote('cloudlens-se'));
    lines.push('');
    lines.push('# ----- EC2 Key Pair (must exist in target region) -----');
    lines.push('key_pair_name = ' + quote('your-ec2-key-pair'));
    lines.push('');
    lines.push('# ----- Network ACL (allowed source CIDRs) -----');
    lines.push('allowed_ssh_cidrs = [');
    cidrList.forEach(function (c, i) {
      lines.push('  ' + quote(c) + (i < cidrList.length - 1 ? ',' : ''));
    });
    lines.push(']');
    lines.push('allowed_web_cidrs = [');
    cidrList.forEach(function (c, i) {
      lines.push('  ' + quote(c) + (i < cidrList.length - 1 ? ',' : ''));
    });
    lines.push(']');
    lines.push('');
    if (modeVal === 'existing-vpc' || modeVal === 'jumpbox') {
      lines.push('# ----- Existing VPC mode (brownfield) -----');
      lines.push('# Uncomment + fill these to deploy into an existing VPC');
      lines.push('# vpc_id     = ' + quote('vpc-0xxxxxxxxxxxxxxxx'));
      lines.push('# subnet_ids = [');
      lines.push('#   ' + quote('subnet-0xxxxxxxxxxxxxxxx') + ',  # mgmt');
      lines.push('#   ' + quote('subnet-0xxxxxxxxxxxxxxxx') + ',  # data');
      lines.push('#   ' + quote('subnet-0xxxxxxxxxxxxxxxx') + '   # tool');
      lines.push('# ]');
    } else {
      lines.push('# ----- Greenfield VPC (new) -----');
      lines.push('vpc_cidr        = ' + quote('10.0.0.0/16'));
      lines.push('mgmt_subnet_cidr = ' + quote('10.0.1.0/24'));
      lines.push('data_subnet_cidr = ' + quote('10.0.2.0/24'));
      lines.push('tool_subnet_cidr = ' + quote('10.0.3.0/24'));
    }
    lines.push('');
    lines.push('# ----- Marketplace AMIs (CRITICAL — instance-type restrictions) -----');
    lines.push('kvo_instance_type  = ' + quote('c5.2xlarge')  + '  # KVO Marketplace: c5.2xlarge ONLY');
    lines.push('clms_instance_type = ' + quote('t3.xlarge')   + '  # CLMS: t3.xlarge recommended');
    lines.push('vpb_instance_type  = ' + quote('t3.xlarge')   + '  # vPB-KVO Marketplace: t3.xlarge ONLY');
    lines.push('');
    lines.push('# ----- Auto-Mirror Lambda (CloudFormation path only) -----');
    lines.push('enable_auto_mirror = true');
    lines.push('');
    lines.push('# ----- Resource Tags -----');
    lines.push('tags = {');
    tagPairs.forEach(function (kv) {
      lines.push('  ' + kv[0] + ' = ' + quote(kv[1]));
    });
    lines.push('}');
    lines.push('');
    lines.push('# ----- Phase 2 Manual Configuration Reference -----');
    lines.push('# These are NOT terraform variables — kept here as deployment notes:');
    lines.push('#   CLMS public IP:     ' + clmsIpVal);
    lines.push('#   CLMS project key:   ' + projKeyVal);
    lines.push('#   vPB SSH port:       9022   (NOT 22)');
    lines.push('#   KVO default login:  admin / admin   (change on first login)');
    lines.push('#   CLMS default login: admin / Cl0udLens@dm!n');
    return lines.join('\n');
  }

  function span(cls, text) {
    var s = document.createElement('span');
    s.className = cls;
    s.textContent = text;
    return s;
  }

  // Tokenize a single .tfvars line into safe DOM nodes (no innerHTML).
  function appendLine(parent, line) {
    // Comment line
    var commentMatch = line.match(/^(\s*)(#.*)$/);
    if (commentMatch) {
      if (commentMatch[1]) parent.appendChild(document.createTextNode(commentMatch[1]));
      parent.appendChild(span('yc', commentMatch[2]));
      return;
    }
    // Terraform key = value pattern
    var keyMatch = line.match(/^(\s*)([a-zA-Z_][\w-]*)(\s*=\s*)(.*)$/);
    var rest = line;
    if (keyMatch) {
      parent.appendChild(document.createTextNode(keyMatch[1]));
      parent.appendChild(span('yk', keyMatch[2]));
      parent.appendChild(document.createTextNode(keyMatch[3]));
      rest = keyMatch[4];
    }
    // Highlight quoted string values
    var re = /"(?:[^"\\]|\\.)*"/g;
    var last = 0;
    var m;
    while ((m = re.exec(rest)) !== null) {
      if (m.index > last) parent.appendChild(document.createTextNode(rest.slice(last, m.index)));
      parent.appendChild(span('yv', m[0]));
      last = m.index + m[0].length;
    }
    if (last < rest.length) parent.appendChild(document.createTextNode(rest.slice(last)));
  }

  function refresh() {
    if (!tfvarsOut) return;
    var t = buildTfvars();
    while (tfvarsOut.firstChild) tfvarsOut.removeChild(tfvarsOut.firstChild);
    var lines = t.split('\n');
    for (var i = 0; i < lines.length; i++) {
      appendLine(tfvarsOut, lines[i]);
      if (i < lines.length - 1) tfvarsOut.appendChild(document.createTextNode('\n'));
    }
  }

  [clmsIp, projKey, tags, rgs, mode].forEach(function (el) {
    if (el) el.addEventListener('input', refresh);
    if (el && el.tagName === 'SELECT') el.addEventListener('change', refresh);
  });

  // password toggle
  var togKey = document.getElementById('toggle-key');
  if (togKey && projKey) {
    togKey.addEventListener('click', function () {
      projKey.type = projKey.type === 'password' ? 'text' : 'password';
    });
  }

  // download — now emits terraform.tfvars
  var dl = document.getElementById('download-yaml'); // keep ID, change behaviour
  if (dl) {
    var dlLabel = dl.querySelector('.label, span');
    if (dlLabel) dlLabel.textContent = 'Download terraform.tfvars';
    dl.addEventListener('click', function () {
      var t = buildTfvars();
      var blob = new Blob([t], { type: 'text/plain' });
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url; a.download = 'terraform.tfvars';
      document.body.appendChild(a); a.click();
      document.body.removeChild(a);
      setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
      flash('Downloaded terraform.tfvars');
    });
  }

  // ----- COPY BUTTONS (data-copy="<id>" -> copies that element's text) -----
  document.querySelectorAll('.copy-btn[data-copy]').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var target = document.getElementById(btn.getAttribute('data-copy'));
      if (!target) return;
      var text = target.innerText || target.textContent || '';
      var done = function () {
        var orig = btn.textContent;
        btn.textContent = 'Copied!';
        btn.classList.add('copied');
        setTimeout(function () {
          btn.textContent = orig;
          btn.classList.remove('copied');
        }, 1600);
      };
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(done, function () { legacyCopy(text); done(); });
      } else { legacyCopy(text); done(); }
    });
  });

  function legacyCopy(text) {
    var ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed'; ta.style.opacity = '0';
    document.body.appendChild(ta); ta.select();
    try { document.execCommand('copy'); } catch (e) {}
    document.body.removeChild(ta);
  }

  // Hero "Run in CloudShell" — copies the curl command
  var cp = document.getElementById('copy-curl');
  if (cp) {
    cp.addEventListener('click', function () {
      var cmd = 'curl -sSL https://raw.githubusercontent.com/Keysight-Tech/cloudlens-autopilot/main/quickstart.sh | bash';
      if (navigator.clipboard) {
        navigator.clipboard.writeText(cmd).then(function () { flash('Copied curl command to clipboard'); });
      } else { legacyCopy(cmd); flash('Copied curl command'); }
    });
  }

  function flash(msg) {
    var f = document.getElementById('copy-feedback');
    if (!f) return;
    f.textContent = msg;
    setTimeout(function () { f.textContent = ''; }, 2400);
  }

  // ----- SCALING SLIDER (now keyed to E1S/E50 fleet projections) -----
  var slider = document.getElementById('vm-count');
  var vmReadout = document.getElementById('vm-readout');
  var forksReadout = document.getElementById('forks-readout');
  var shardedReadout = document.getElementById('sharded-readout');
  var timeReadout = document.getElementById('time-readout');
  var bars = document.querySelectorAll('.scale-bar');

  function fmt(n) { return n.toLocaleString('en-US'); }

  // Updated bands keyed to AutoPilot's documented sensor deployment scaling
  function bandFor(n) {
    if (n <= 50)     return { time: '5 to 10 min',   forks: 50,   sharded: false, level: 0 };
    if (n <= 200)    return { time: '10 to 20 min',  forks: 100,  sharded: false, level: 1 };
    if (n <= 800)    return { time: '15 to 30 min',  forks: 200,  sharded: false, level: 2 };
    if (n <= 2000)   return { time: '30 to 60 min',  forks: 400,  sharded: true,  level: 3 };
    if (n <= 5000)   return { time: '1 to 2 hours',  forks: 800,  sharded: true,  level: 4 };
    if (n <= 10000)  return { time: '2 to 4 hours',  forks: 1500, sharded: true,  level: 5 };
    return            { time: '4+ hours',           forks: 2500, sharded: true,  level: 6 };
  }

  function updateScaling() {
    if (!slider) return;
    var n = Number(slider.value || 0);
    var b = bandFor(n);
    if (vmReadout) vmReadout.textContent = fmt(n);
    if (forksReadout) forksReadout.textContent = fmt(b.forks);
    if (shardedReadout) shardedReadout.textContent = b.sharded ? 'Yes' : 'No';
    if (timeReadout) timeReadout.textContent = b.time;
    bars.forEach(function (bar) {
      var bl = Number(bar.getAttribute('data-band-level') || 0);
      if (bl <= b.level) bar.classList.add('active');
      else bar.classList.remove('active');
    });
  }
  if (slider) {
    slider.addEventListener('input', updateScaling);
    updateScaling();
  }

  // ----- SMOOTH SCROLL -----
  document.querySelectorAll('a[href^="#"]').forEach(function (a) {
    a.addEventListener('click', function (e) {
      var id = a.getAttribute('href').slice(1);
      var el = document.getElementById(id);
      if (!el) return;
      e.preventDefault();
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      if (history.replaceState) history.replaceState(null, '', '#' + id);
    });
  });

  // ----- INITIAL RENDER -----
  refresh();
})();
