/* CloudLens Ansible for Azure: landing site behaviors */
(function () {
  'use strict';

  // ----- THEME -----
  // Default to light mode on first visit. If the user explicitly toggles to
  // dark, that preference is saved to localStorage and respected on return.
  // We intentionally ignore the OS prefers-color-scheme on first paint so the
  // landing experience is consistent for every customer.
  var root = document.documentElement;
  var stored = localStorage.getItem('cl-theme');
  var theme = stored || 'light';
  root.setAttribute('data-theme', theme);

  var toggle = document.getElementById('theme-toggle');
  if (toggle) {
    toggle.addEventListener('click', function () {
      var next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', next);
      localStorage.setItem('cl-theme', next);
    });
  }

  // ----- WIZARD: live YAML preview -----
  var clmsIp = document.getElementById('clms-ip');
  var projKey = document.getElementById('project-key');
  var tags = document.getElementById('tags');
  var rgs = document.getElementById('rgs');
  var mode = document.getElementById('mode');
  var yamlOut = document.getElementById('yaml-preview');

  function quote(s) { return '"' + String(s).replace(/"/g, '\\"') + '"'; }

  function buildYaml() {
    var ip = clmsIp.value.trim() || '10.0.0.10';
    var key = projKey.value.trim() || 'paste-from-clms-projects-api-keys';
    var tagsValue = tags.value.trim() || 'Env=Azure';
    var rgList = rgs.value.split(',').map(function (s) { return s.trim(); }).filter(Boolean);
    var connMode = mode.value || 'direct_public';

    var tagsObj = {};
    tagsValue.split(',').forEach(function (pair) {
      var p = pair.trim();
      if (!p) return;
      var eq = p.indexOf('=');
      if (eq > 0) tagsObj[p.slice(0, eq).trim()] = p.slice(eq + 1).trim();
    });

    var lines = [];
    lines.push('# customer_input.yaml');
    lines.push('# generated by keysight-tech.github.io/cloudlens-ansible-azure');
    lines.push('');
    lines.push('clms:');
    lines.push('  ip: ' + quote(ip));
    lines.push('  project_key: ' + quote(key));
    lines.push('');
    lines.push('connection:');
    lines.push('  mode: ' + quote(connMode));
    if (connMode === 'jumpbox') {
      lines.push('  jumpbox_host: "jumpbox.example.com"');
      lines.push('  jumpbox_user: "azureuser"');
    } else if (connMode === 'bastion') {
      lines.push('  bastion_name: "<bastion-resource-name>"');
      lines.push('  bastion_rg: "<bastion-resource-group>"');
    }
    lines.push('');
    lines.push('container:');
    lines.push('  runtime: "auto"');
    lines.push('');
    lines.push('tags:');
    Object.keys(tagsObj).forEach(function (k) {
      lines.push('  ' + k + ': ' + quote(tagsObj[k]));
    });
    if (!Object.keys(tagsObj).length) lines.push('  Env: "Azure"');
    lines.push('');
    if (rgList.length) {
      lines.push('azure:');
      lines.push('  resource_groups:');
      rgList.forEach(function (r) { lines.push('    - ' + quote(r)); });
    } else {
      lines.push('azure:');
      lines.push('  resource_groups: []  # empty = scan whole subscription');
    }
    return lines.join('\n');
  }

  function span(cls, text) {
    var s = document.createElement('span');
    s.className = cls;
    s.textContent = text;
    return s;
  }

  // Tokenize a single line into safe DOM nodes (no innerHTML, no HTML strings).
  function appendLine(parent, line) {
    // Comment line
    var commentMatch = line.match(/^(\s*)(#.*)$/);
    if (commentMatch) {
      if (commentMatch[1]) parent.appendChild(document.createTextNode(commentMatch[1]));
      parent.appendChild(span('yc', commentMatch[2]));
      return;
    }
    // Detect key: value pattern (preserve leading whitespace)
    var keyMatch = line.match(/^(\s*-?\s*)([a-zA-Z_][\w-]*)(:)(.*)$/);
    var rest = line;
    if (keyMatch) {
      parent.appendChild(document.createTextNode(keyMatch[1]));
      parent.appendChild(span('yk', keyMatch[2]));
      parent.appendChild(document.createTextNode(keyMatch[3]));
      rest = keyMatch[4];
    }
    // Highlight quoted string values within `rest`
    var re = /"(?:[^"\\]|\\.)*"/g;
    var last = 0;
    var m;
    while ((m = re.exec(rest)) !== null) {
      if (m.index > last) parent.appendChild(document.createTextNode(rest.slice(last, m.index)));
      parent.appendChild(span('yv', m[0]));
      last = m.index + m[0].length;
    }
    if (last < rest.length) parent.appendChild(document.createTextNode(rest.slice(last)));
  }

  function refresh() {
    if (!yamlOut) return;
    var y = buildYaml();
    // Clear existing content safely.
    while (yamlOut.firstChild) yamlOut.removeChild(yamlOut.firstChild);
    var lines = y.split('\n');
    for (var i = 0; i < lines.length; i++) {
      appendLine(yamlOut, lines[i]);
      if (i < lines.length - 1) yamlOut.appendChild(document.createTextNode('\n'));
    }
  }

  [clmsIp, projKey, tags, rgs, mode].forEach(function (el) {
    if (el) el.addEventListener('input', refresh);
    if (el && el.tagName === 'SELECT') el.addEventListener('change', refresh);
  });

  // password toggle
  var togKey = document.getElementById('toggle-key');
  if (togKey && projKey) {
    togKey.addEventListener('click', function () {
      projKey.type = projKey.type === 'password' ? 'text' : 'password';
    });
  }

  // download
  var dl = document.getElementById('download-yaml');
  if (dl) {
    dl.addEventListener('click', function () {
      var y = buildYaml();
      var blob = new Blob([y], { type: 'text/yaml' });
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url; a.download = 'customer_input.yaml';
      document.body.appendChild(a); a.click();
      document.body.removeChild(a);
      setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
      flash('Downloaded customer_input.yaml');
    });
  }

  // ----- COPY BUTTONS (data-copy="<id>" -> copies that element's text) -----
  document.querySelectorAll('.copy-btn[data-copy]').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var target = document.getElementById(btn.getAttribute('data-copy'));
      if (!target) return;
      var text = target.innerText || target.textContent || '';
      var done = function () {
        var original = btn.getAttribute('data-original') || btn.textContent;
        if (!btn.getAttribute('data-original')) btn.setAttribute('data-original', original);
        btn.textContent = 'Copied!';
        btn.classList.add('copied');
        setTimeout(function () {
          btn.textContent = original;
          btn.classList.remove('copied');
        }, 2000);
      };
      if (navigator.clipboard && window.isSecureContext !== false) {
        navigator.clipboard.writeText(text).then(done, function () {
          // fall through to legacy path on rejection
          legacyCopy(text); done();
        });
      } else {
        legacyCopy(text); done();
      }
    });
  });

  function legacyCopy(text) {
    var ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand('copy'); } catch (e) { /* ignore */ }
    document.body.removeChild(ta);
  }

  // copy curl
  var cp = document.getElementById('copy-curl');
  if (cp) {
    cp.addEventListener('click', function () {
      var cmd = 'curl -sSL https://raw.githubusercontent.com/Keysight-Tech/cloudlens-ansible-azure/main/quickstart.sh | bash';
      if (navigator.clipboard) {
        navigator.clipboard.writeText(cmd).then(function () { flash('Copied curl command to clipboard'); });
      } else {
        var ta = document.createElement('textarea');
        ta.value = cmd; document.body.appendChild(ta);
        ta.select(); document.execCommand('copy'); document.body.removeChild(ta);
        flash('Copied curl command to clipboard');
      }
    });
  }

  function flash(msg) {
    var f = document.getElementById('copy-feedback');
    if (!f) return;
    f.textContent = msg;
    setTimeout(function () { f.textContent = ''; }, 2400);
  }

  refresh();

  // ----- SCALING VISUALIZER -----
  var vmCount = document.getElementById('vm-count');
  var vmReadout = document.getElementById('vm-readout');
  var forksReadout = document.getElementById('forks-readout');
  var shardedReadout = document.getElementById('sharded-readout');
  var timeReadout = document.getElementById('time-readout');
  var bars = document.querySelectorAll('.scale-bars .bar');

  function fmt(n) { return n.toLocaleString('en-US'); }

  function bandFor(n) {
    if (n <= 50) return { id: '1-50', forks: 20, sharded: false, time: '5 to 10 min' };
    if (n <= 500) return { id: '50-500', forks: 50, sharded: false, time: '15 to 30 min' };
    if (n <= 2000) return { id: '500-2000', forks: 200, sharded: false, time: '30 to 60 min' };
    if (n <= 10000) return { id: '2000-10000', forks: 500, sharded: true, time: '30 to 60 min (sharded)' };
    return { id: '10000+', forks: 1000, sharded: true, time: '1 to 2 hr (AWX)' };
  }

  function updateScaling() {
    if (!vmCount) return;
    var n = parseInt(vmCount.value, 10);
    var b = bandFor(n);
    if (vmReadout) vmReadout.textContent = fmt(n);
    if (forksReadout) forksReadout.textContent = b.sharded ? (b.forks + '/shard') : fmt(b.forks);
    if (shardedReadout) shardedReadout.textContent = b.sharded ? 'Yes' : 'No';
    if (timeReadout) timeReadout.textContent = b.time;
    bars.forEach(function (bar) {
      bar.classList.toggle('active', bar.getAttribute('data-band') === b.id);
    });
  }
  if (vmCount) {
    vmCount.addEventListener('input', updateScaling);
    updateScaling();
  }

  // ----- SMOOTH NAV: header offset -----
  document.querySelectorAll('a[href^="#"]').forEach(function (a) {
    a.addEventListener('click', function (e) {
      var id = a.getAttribute('href');
      if (id.length <= 1) return;
      var el = document.querySelector(id);
      if (!el) return;
      e.preventDefault();
      var rect = el.getBoundingClientRect();
      var top = window.pageYOffset + rect.top - 70;
      window.scrollTo({ top: top, behavior: 'smooth' });
      history.replaceState(null, '', id);
    });
  });

  // ----- BUTTON RIPPLE -----
  document.querySelectorAll('.btn').forEach(function (btn) {
    btn.addEventListener('click', function (e) {
      var r = btn.getBoundingClientRect();
      var ripple = document.createElement('span');
      ripple.style.cssText = 'position:absolute;border-radius:50%;pointer-events:none;background:rgba(255,255,255,0.4);transform:scale(0);animation:cl-ripple .6s ease-out;left:' + (e.clientX - r.left - 10) + 'px;top:' + (e.clientY - r.top - 10) + 'px;width:20px;height:20px;';
      btn.appendChild(ripple);
      setTimeout(function () { ripple.remove(); }, 650);
    });
  });

  var style = document.createElement('style');
  style.textContent = '@keyframes cl-ripple { to { transform: scale(20); opacity: 0; } }';
  document.head.appendChild(style);
})();
